development:
  adapter: postgresql
  encoding: unicode
  database: q_and_a_development
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: q_and_a_test
  pool: 5
  username: kellywaters
  password: 